# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1STJVX8BRd5bOAwH92w6U8mrmAN7v5x_Q
"""

import sklearn.metrics as metrics
import numpy as np
import torch

def getmetrics(pred,truth):
    print('get metrics with test data...')
    mae = metrics.mean_absolute_error(truth,pred)
    mse = metrics.mean_squared_error(truth,pred)
    rmse = mse**0.5
    nrmse = rmse/np.mean(truth)
    r2 = metrics.r2_score(truth,pred)
 
    return mae,mse,rmse,nrmse,r2

"""这个文件是用来计算误差、精确度的。"""