# -*- coding: utf-8 -*-
"""show.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKQrSHz_n3uzmus0Vo-4VKUGcpJB8mqb
"""


import numpy as np
import matplotlib.pyplot as plt

def get_flow(file_name): #将读取文件写成一个函数
    flow_data=np.load(file_name) #载入交通流量数据
    print([key for key in flow_data.keys()]) #打印看看key是什么

    print(flow_data['data'].shape) #(16992, 307, 3)，16992是时间(59*24*12), 307是节点数，3表示每一维特征的维度
    flow_data=flow_data['data'] #[T,N,D]T为时间，N为节点数，D为节点特征
    return flow_data

#做工程、项目等第一步对拿来的数据进行可视化的直观分析
if __name__ == "__main__":
    traffic_data=get_flow("/content/drive/MyDrive/transformer/PeMS04/pems04_all.npz")
    node_id=10
    print(traffic_data.shape)

    plt.plot(traffic_data[:24*12,node_id,0]) #0维特征
    plt.savefig("node_{:3d}_1.png".format(node_id))

    plt.plot(traffic_data[:24*12,node_id,1]) #1维特征
    plt.savefig("node_{:3d}_2.png".format(node_id))

    plt.plot(traffic_data[:24*12,node_id,2]) #2维特征
    plt.savefig("node_{:3d}_3.png".format(node_id))

"""这个文件应该只是为了数据可视化，因为数据集的结构不一样，这一块和ST-Tran的代码完全不一样。"""